# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 15:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
