# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='skype',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
