# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 00:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GkgCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numarts', models.IntegerField()),
                ('counttype', models.CharField(max_length=64)),
                ('number', models.IntegerField()),
                ('objecttype', models.CharField(max_length=128)),
                ('geo_type', models.IntegerField()),
                ('geo_fullname', models.CharField(max_length=256)),
                ('geo_countrycode', models.CharField(max_length=2)),
                ('geo_adm1code', models.CharField(max_length=4)),
                ('geo_lat', models.FloatField()),
                ('geo_long', models.FloatField()),
                ('geo_featureid', models.CharField(max_length=256)),
                ('cameoeventids', models.CharField(max_length=256)),
                ('sources', models.CharField(max_length=256)),
                ('sourceurls', models.CharField(max_length=512)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
