# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgcounts',
            name='cameoeventids',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='gkgcounts',
            name='counttype',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='gkgcounts',
            name='sources',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='gkgcounts',
            name='sourceurls',
            field=models.CharField(max_length=1024),
        ),
    ]
