# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0002_auto_20160407_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgcounts',
            name='geo_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gkgcounts',
            name='geo_long',
            field=models.FloatField(null=True),
        ),
    ]
