# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0003_auto_20160407_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgcounts',
            name='geo_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='gkgcounts',
            name='geo_long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
