# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0007_auto_20160407_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gkgcounts',
            name='cameoeventids',
        ),
        migrations.AlterField(
            model_name='gkgcounts',
            name='sourceurls',
            field=models.CharField(max_length=4096),
        ),
    ]
