# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0008_auto_20160407_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gkgcounts',
            name='sources',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gkgcounts',
            name='sourceurls',
            field=models.TextField(),
        ),
    ]
