# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0012_auto_20160412_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=16, null=True)),
                ('Name', models.CharField(max_length=256, null=True)),
                ('CountryCode', models.CharField(max_length=3, null=True)),
                ('KnownGroupCode', models.CharField(max_length=3, null=True)),
                ('EthnicCode', models.CharField(max_length=3, null=True)),
                ('Religion1Code', models.CharField(max_length=3, null=True)),
                ('Religion2Code', models.CharField(max_length=3, null=True)),
                ('Type1Code', models.CharField(max_length=3, null=True)),
                ('Type2Code', models.CharField(max_length=3, null=True)),
                ('Type3Code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('GLOBALEVENTID', models.IntegerField(primary_key=True, serialize=False)),
                ('SQLDATE', models.CharField(max_length=8)),
                ('MonthYear', models.CharField(max_length=6)),
                ('Year', models.CharField(max_length=4)),
                ('FractionDate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('IsRootEvent', models.BooleanField()),
                ('EventCode', models.IntegerField()),
                ('EventBaseCode', models.IntegerField()),
                ('EventRootCode', models.IntegerField()),
                ('QuadClass', models.IntegerField()),
                ('GoldsteinScale', models.DecimalField(decimal_places=1, max_digits=3)),
                ('NumMentions', models.IntegerField()),
                ('NumSources', models.IntegerField()),
                ('NumArticles', models.IntegerField()),
                ('AvgTone', models.DecimalField(decimal_places=12, max_digits=15)),
                ('DATEADDED', models.DateField()),
                ('SOURCEURL', models.URLField(max_length=1024)),
                ('Actor1', models.ManyToManyField(related_name='Actor1', to='GDELT.Actor')),
                ('Actor2', models.ManyToManyField(related_name='Actor2', to='GDELT.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField()),
                ('FullName', models.CharField(max_length=512, null=True)),
                ('CountryCode', models.CharField(max_length=2, null=True)),
                ('ADM1Code', models.CharField(max_length=4, null=True)),
                ('Lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('Long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('FeatureID', models.CharField(max_length=16, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.RenameModel(
            old_name='GDELTFiles',
            new_name='GDELTFile',
        ),
        migrations.RenameModel(
            old_name='GkgCounts',
            new_name='GkgCount',
        ),
        migrations.AddField(
            model_name='event',
            name='Geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDELT.Geo'),
        ),
        migrations.AddField(
            model_name='actor',
            name='Geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GDELT.Geo'),
        ),
    ]
