# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0015_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('label', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
