# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0021_auto_20160413_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='Code',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
