# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0024_auto_20160413_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='SQLDATE',
            field=models.DateField(),
        ),
    ]
