# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0026_auto_20160413_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('label', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='CountryCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GDELT.Country'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='EthnicCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GDELT.EthnicGroup'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='KnownGroupCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GDELT.KnownGroup'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='Religion1Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Religion1', to='GDELT.Religion'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='Religion2Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Religion2', to='GDELT.Religion'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='Type1Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type1', to='GDELT.Type'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='Type2Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type2', to='GDELT.Type'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='Type3Code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type3', to='GDELT.Type'),
        ),
    ]
