# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDELT', '0027_auto_20160413_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='Uname',
            field=models.CharField(default='::::::', max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='Code',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='Name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
