# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_contact_skype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.Contact')),
                ('name', models.CharField(max_length=256)),
                ('picture', models.URLField(max_length=256)),
                ('title', models.CharField(max_length=256)),
            ],
            bases=('contacts.contact',),
        ),
    ]
