# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contacts.Contact')),
            ],
            bases=('contacts.contact',),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organization'),
        ),
    ]
